package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE6F2EF)
val md_theme_light_onPrimaryContainer = Color(0xFF00201C)
val md_theme_light_secondary = Color(0xFFDBE5E0)
val md_theme_light_onSecondary = Color(0xFF1C1D1B)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E3)
val md_theme_light_onSecondaryContainer = Color(0xFF00201C)
val md_theme_light_tertiary = Color(0xFF39656B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBF2)
val md_theme_light_onTertiaryContainer = Color(0xFF001F23)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF4F9F8)
val md_theme_light_onBackground = Color(0xFF1C1D1B)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1D1B)
val md_theme_light_surfaceVariant = Color(0xFFF0F4F3)
val md_theme_light_onSurfaceVariant = Color(0xFF5C635E)
val md_theme_light_outline = Color(0xFFEDF1F0)

val md_theme_dark_primary = Color(0xFF006B5E)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFFE6F2EF)
val md_theme_dark_onPrimaryContainer = Color(0xFF00201C)
val md_theme_dark_secondary = Color(0xFFDBE5E0)
val md_theme_dark_onSecondary = Color(0xFF1C1D1B)
val md_theme_dark_secondaryContainer = Color(0xFFCCE8E3)
val md_theme_dark_onSecondaryContainer = Color(0xFF00201C)
val md_theme_dark_tertiary = Color(0xFF39656B)
val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
val md_theme_dark_tertiaryContainer = Color(0xFFBCEBF2)
val md_theme_dark_onTertiaryContainer = Color(0xFF001F23)
val md_theme_dark_error = Color(0xFFBA1A1A)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_background = Color(0xFFF4F9F8)
val md_theme_dark_onBackground = Color(0xFF1C1D1B)
val md_theme_dark_surface = Color(0xFFFFFFFF)
val md_theme_dark_onSurface = Color(0xFF1C1D1B)
val md_theme_dark_surfaceVariant = Color(0xFFF0F4F3)
val md_theme_dark_onSurfaceVariant = Color(0xFF5C635E)
val md_theme_dark_outline = Color(0xFFEDF1F0)
